export const levelOne = [
  "Gimana first impression aku?",
  "Menurut kamu kerjaan aku susah atau enggak?",
  "Apa menurutmu bagian yang paling sulit dari pekerjaanku?",
  "Apakah aku terlihat seperti seseorang yang kreatif atau analitis?",
  "Menurut kamu, aku pernah ketilang berapa kali?",
  "Menurutmu, apakah aku terlihat seperti seseorang yang mau tato?",
  "Menurut kamu apakah aku orangnya boros?",
  "Apakah menurut kamu aku pernah buka-buka/razia HP pacar?",
  "Apa hal pertama yang pertama kali kamu perhatiin tentang aku?",
  "Menurut kamu aku lebih suka teh atau kopi?",
  "Jika kamu mau beli hadiah buat aku, tanpa tahu apa-apa kecuali penampilanku, apa yang akan kamu belikan?",
  "Apa yang wallpaperku katakan tentangku?",
  "Apakah aku terlihat ramah?",
  "Apakah menurutmu aku mudah jatuh cinta? mengapa atau mengapa tidak?",
  "Ketika aku masih kecil, cita-cita aku menurut kamu apa?",
  "Menurut kamu, aku orangnya tepat waktu atau telatan?",
  "Mata pelajaran apa yang menurutmu aku senang?",
  "Pujian apa yang menurut kamu paling sering aku dengar?",
  "Apakah aku terlihat seperti orang yang suka bangun pagi atau begadang?",
  "Apakah menurut kamu aku terkenal pas SMA?",
  "Apakah menurut kamu aku anaknya bandel?",
  "Apa yang paling aneh atau tidak biasa tentang aku menurut kamu?",
  "Apa yang membuatku menarik menurutmu?",
  "Gaya berpakaianku gimana menurutmu? Apa bisa menebak karakterku dari penampilanku?",
  "Apakah menurut kamu aku pernah patah hati?",
  "Apa asumsi terburuk yang pernah dibuat sama orang tentang diri kamu?",
];

export const levelTwo = [
  "Karakteristik utamamu apa?",
  "Apa pengalaman paling menyakitkan yang pernah kamu alami, non fisik?",
  "Baik-baik saja nggak sih sebenarnya? Boleh jujur.",
  "Apa hal terakhir yang ibumu katakan kepadamu yang ternyata bohong?",
  "Siapa nama ayahmu dan satu hal tentangnya?",
  "Apa yang dulu aku toleransi dari orang lain tapi sekarang tak lagi memberi ruang?",
  "Sesuatu yang membuatku tersenyum minggu ini adalah ___.",
  "Apa yang sering kamu rasakan belakangan ini?",
  "Apa yang kamu butuhkan saat ini tapi belum kamu sampaikan?",
  "Ada hal apa yang sedang kamu hadapi tapi tak terlihat oleh orang lain?",
  "Apa peristiwa terbesar yang mengubah hidup cintamu?",
  "Apa kata hatimu?",
  "Apa kebiasaan buruk terbesarmu yang bisa kamu akui?",
  "Siapa orang dalam hidupmu yang pantas mendapat ucapan terima kasih terbesar? Beritahu mereka jika bisa.",
  "Apa yang sedang kamu overthinking kan sekarang?",
  "Apa yang kamu pelajari tentang dirimu dari hubunganmu yang lalu?",
  "Kepercayaan apakah tentang dirimu yang tidak lagi berguna?",
  "Apa yang perlu kamu maafkan dari dirimu sendiri?",
  "Pelajaran cinta terberat yang pernah kamu alami adalah apa?",
  "Siapa orang di hidupmu yang kamu merasa bisa tampil paling vulnerable?",
  "Kepribadian orangtuamu, mana yang ingin kamu jaga/lepas?",
  "Dear diriku yang lebih muda: ____.",
  "Pikirkan seseorang yang kamu kagumi. Mengapa orang ini terlintas di pikiranmu?",
  "Bagian kesukaanmu tentang dirimu sendiri yang bukan hal fisik apa?",
  "Apa yang paling sulit dari pacaran sama kamu?",
  "Apa yang kamu pelajari tentang dirimu minggu ini?",
  "Apa pelajaran dari pengalaman paling menyakitkanmu?",
  "Bagaimana kamu move on dari cinta pertama kamu?",
  "Pelajaran terbaik apa yang pernah diajarkan mantan pada kamu?",
  "Apakah ada seseorang yang telah mengubah hidupmu, tetapi ia tidak tahu?",
  "Apa yang paling kamu butuhkan saat ini, lebih dari apapun?",
  "Kapan terakhir kali kamu merasa beruntung menjadi dirimu sendiri?",
  "Kapan terakhir kali kamu merasa paling menjadi diri sendiri?",
];

export const levelThree = [
  "What can I help you with?",
  "Why do you think we met?",
  "What about me surprised you?",
  "In a word, how would you describe our conversation?",
  "What do you think my strength is?",
  "What can I teach you?",
  "Based on what you've learned about me, do you have any Netflix recommendations?",
  "Who do I remind you of?",
  "What can you be kinder towards yourself for today?",
  "What's one small thing you can do to be a better person in 2019?",
  "What can we create together?",
  "How would you describe me to a stranger?",
  "What about me most surprised you?",
  "What would be the perfect gift for me?",
  "What do you admire most about me?",
  "Based on what you learned about me, what book would you recommend I read?",
  "What about me is hardest for you to understand?",
  "What am I most qualified to give advice about?",
  "What is one thing you think I can do that would dramatically improve my life?",
  "If we were in a band, what would our name be?",
  "Based on what you learned about me, does my social media accurately reflect who I am? Why or why not?",
  "What do I need to hear right now?",
  "Based on what you know about me, do you have any netflix recommendations?",
  "What do you think my superpower is?",
  "What is a lesson you will take away from our conversation?",
  "When in this game did you feel most connected to me?",
  "How does one earn your vulnerability? Have I earned it? How can I earn more?",
  "What do you think our most important similarity is?",
  "In one word, how would you describe our conversation?",
  "What answer of mine made you light up?",
  "When this game is over, what will you remember about me?",
  "What question were you most afraid to answer?",
  "What parts of yourself do you see in me?",
  "How do our personalities complement each other?",
  "What do you think my weakness is?",
  "What would make you feel closer to me?",
  "What do you think I fear the most?",
  "What has this conversation taught you about yourself?",
  "What do you think I should know about myself that perhaps I'm unaware of?",
  "What do you think my defining characterisitic is?",
  "Do you believe everyone has a calling? If so, do you think I've found mine?",
  "What do you recommend I let go of, if anything?",
  "In one word, describe how you feel right now",
];
